spring.application.name=logistics-shipments-service


# Client URL
user-service.url=http://localhost:8082/
jwt.token.dev=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInNjb3BlIjoiUk9MRV9BRE1JTiIsImlzcyI6ImNvbS50ZHR1LmxvZ2lzdGljcyIsImV4cCI6MTczMzg0NTUyNywiaWF0IjoxNzMzNzU5MTI3LCJqdGkiOiJkMWFhZjQ5My05YjhjLTQ3YTEtOThlOS1mZTc0YTQwZjBhMDgifQ.mABEYKJJBJK75yBhcvbtXSPk2T6JitqhOcl15H-HQeu2bfJsAwN7b4ifjnpJi-Am6pqOOgvn04fj6TWygnWXow
