plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.0'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.tdtu'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Temporal SDK với gRPC và protobuf được ép buộc sử dụng phiên bản an toàn hơn
	implementation 'io.temporal:temporal-sdk:1.23.0'
	implementation 'com.google.protobuf:protobuf-java:4.28.2' // Sử dụng phiên bản đã vá lỗi
	implementation 'io.grpc:grpc-protobuf:1.56.2' // Ép buộc gRPC an toàn hơn
	implementation 'io.grpc:grpc-netty:1.56.2' // Nếu cần Netty cho gRPC

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
