export enum OrderStatus {
  RECEIVED = "RECEIVED",
  PICKING = "PICKING",
  PICKED = "PICKED",
  TRANSPORTING = "TRANSPORTING",
  DELIVERING = "DELIVERING",
  RE_DELIVERY = "RE_DELIVERY",
  DELIVERED = "DELIVERED",
  PROCESSING = "PROCESSING",
  DRAFT = "DRAFT",
  FAILED_PICKUP = "FAILED_PICKUP",
  APPROVED_RETURN = "APPROVED_RETURN",
  RETURNED = "RETURNED",
  CANCELLED_DELIVERY = "CANCELLED_DELIVERY",
  RETURNING = "RETURNING",
  CONTINUED_DELIVERY = "CONTINUED_DELIVERY",
  VTP_CANCEL_PICKUP = "VTP_CANCEL_PICKUP"
}