export enum OrderStatus {
  PENDING = "Chờ xử lý",
  RECEIVED = "Đã tiếp nhận",
  GETTING_ITEMS = "Đang lấy hàng",
  ITEMS_GOT = "Đã lấy hàng",
  IN_SHIPPING = "Đang vận chuyển",
  OUT_FOR_DELIVERY = "Đang giao hàng",
  WAITING_RETRY = "Chờ phát lại",
  DELIVERY_SUCCESS = "Giao thành công",
  PROCESSING = "Đang xử lý",
  FAILED_TO_FETCH = "Lấy không thành công",
  DRAFT = "Đơn nháp",
  APPROVED_COMPLETE = "Đã duyệt hoàn",
  RETURNED = "Đã trả",
  CANCELLED = "Đã hủy giao",
  IN_RETURN = "Đang chuyển hoàn",
  RESCHEDULED = "Phát tiếp",
  VTP_CANCELLED = "VTP hủy lấy",
  SHOP_CANCELLED = "Shop hủy lấy",
  UNDER_VERIFY_COMPENSATION = "Đang xác minh bồi thường",
  COMPENSATED = "Đã bồi thường",
}