
server:
  port: 8888

spring:
  application:
    name: logistic-api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8085
          predicates:
            - Path=/identity/**
